checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  nodes:
    my-tests-with-coverage:
      tests:
        override:
          - command: './run_test.sh'

    tests: true

filter:
    excluded_paths:
        - '*/test/*'
    dependency_paths:
        - 'lib/*'